PIDCMD
Programming-TRIGON/RobotCode2022 pull request #18
Opened 2022-02-23 19:19 UTC by lycaon7

2022-02-23 20:08 UTC, Mboesn requested changes

2022-02-23 20:08 UTC, Mboesn commented on src/main/java/frc/robot/commands/GenericPIDCMD.java
> +public class GenericPIDCMD extends CommandBase {
change to PIDCMD? debate with @laviRZ

2022-02-23 20:08 UTC, Mboesn commented on src/main/java/frc/robot/commands/GenericPIDCMD.java
> +    }
complicated above simple constructor

2022-02-23 20:08 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/PIDSS.java
> +public interface PIDSS extends MovableSubsystem {
change to PIDSubsystem

2022-02-23 20:08 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/loader/LoaderSS.java
>      }
change velocityRPM to `velocity`

2022-02-23 20:08 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/shooter/ShooterSS.java
> +
delete blank line in line 49

2022-02-25 09:22 UTC, Mboesn requested changes

2022-02-25 09:22 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/loader/LoaderSS.java
> +     * @param velocity to be set to the motors in RPM
@ param velocity desired velocity in RPM

2022-02-25 09:22 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/loader/LoaderSS.java
>          motor.setSetpoint(velocity);
Conversions.RPMToFalcon(velocity, 1)

2022-02-25 09:22 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/loader/LoaderSS.java
edit get velocity to Conversions.FalconToRPM(velocity, 1)
and add docs

2022-02-25 09:22 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/shooter/ShooterSS.java
> +     * @param velocity to be set to the motors in RPM
@ param velocity desired velocity in RPM

2022-02-26 19:45 UTC, Mboesn requested changes

2022-02-26 19:45 UTC, Mboesn commented on src/main/java/frc/robot/commands/PIDCommand.java
> +    public PIDCommand(PIDSubsystem subsystem, DoubleSupplier setpoint, BooleanSupplier isFinished) {
docs

2022-02-26 19:45 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/PIDSubsystem.java
> +public interface PIDSubsystem extends MovableSubsystem {
docs

2022-02-26 19:45 UTC, Mboesn commented on src/main/java/frc/robot/subsystems/shooter/ShooterSS.java
> -
why last line deleted

2022-02-26 21:26 UTC, laviRZ requested changes

2022-02-26 21:26 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/intake/IntakeOpenerSS.java
> +    public void setSetpoint(double degree) {
rename parameter to setpoint

2022-02-26 21:26 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/loader/LoaderSS.java
> +    public void setSetpoint(double velocity) {
rename parameter to setpoint

2022-02-26 21:26 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/loader/LoaderSS.java
> +    /**
Returns...

2022-02-26 21:26 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/shooter/ShooterSS.java
> +    public void setSetpoint(double velocity) {
rename parameter to setpoint

2022-02-26 21:32 UTC, lycaon7 commented on src/main/java/frc/robot/commands/PIDCommand.java
> +    public PIDCommand(PIDSubsystem subsystem, DoubleSupplier setpoint) {
git add codereview /.gitignore

2022-02-26 21:57 UTC, laviRZ approved these changes
change and merge

2022-02-26 21:57 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/shooter/ShooterSS.java
> +     * @param setpoint desired velocity in RPM
the desired

2022-02-26 21:57 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/pitcher/PitcherSS.java
> +     * @param setpoint desired angle in degrees
the desired

2022-02-26 21:57 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/loader/LoaderSS.java
> +     * @param setpoint desired velocity in RPM
the desired

2022-02-26 21:57 UTC, laviRZ commented on src/main/java/frc/robot/subsystems/intake/IntakeOpenerSS.java
> +     * @param setpoint desired angle in degrees
the desired

2022-02-26 22:01 UTC, merged